package Datas.enums;

public enum DeviceInfoTypes {

	CREE_COMPTE,
	CONNEXION,
	DECONNEXION,
	CREE_PROJET,
	EFFACE_PROJET,
	MODIFIE_PROJET,
	AJOUT_MEMBRE,
	RETRAIT_MEMBRE,
	CREE_SPRINT,
	EFFACE_SPINT,
	ARCHIVER_SPRINT,
	CREE_TACHE,
	MODIFIE_TACHE,
	SUPPRIMER_TACHE,
	CREE_SOUS_TACHE,
	MODIFIER_SOUS_TACHE,
	SUPPRIMER_SOUS_TACHE,
	SYNCHRONIZE_UP,
	SYNCHRONIZE_DOWN
	
}