package Datas.enums;

public enum DeviceInfoTypes {

	CREE_COMPTE,
	CONNEXION,
	DECONNEXION,
	CREE_PROJET,
	EFFACE_PROJET,
	MODIFIE_PROJET,
	AJOUT_MEMBRE,
	RETRAIT_MEMBRE,
	CREE_SPRINT,
	EFFACE_SPRINT,
	ARCHIVER_SPRINT,
	CREE_TACHE,
	MODIFIE_TACHE,
	SUPPRIMER_TACHE,
	CREE_SOUS_TACHE,
	MODIFIER_SOUS_TACHE,
	SUPPRIMER_SOUS_TACHE,
	SYNCHRONIZE_UP,
	SYNCHRONIZE_DOWN,
	LISTE_MEMBRES,
	AJOUT_MANAGER,
	ALL_USERS,
	IS_MEMBER,
	IS_USER,
}